### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/create-js-project#2]
Rough roadmap for the releases to come:

### v1.0.0
- [x] Basic Templates (#1)
- [x] Complete website
- [x] Complete CLI that looks ok

### v1.1.0
- [ ] Vue.js templates
- [ ] Improved templates with examples

### v1.2.0
- [ ] Angular templates
- [ ] Support for further customization (Sass, Jest possibly)

### v1.3.0
- [ ] TypeScript support
- [ ] Custom template import functionality (#3)
